### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by calle5555** [mimersql/MimerPy#5]
Have installed it using "pip3 install mimerpy" and it is correctly installed. When running "from mimerpy import *" I get the error message "DLL load failed while importing mimerapi: The specified module could not be found."

**Comment by perschr** [comment]
What version of Windows are you using?

Do you have Mimer V11.0.5A installed on the PC?
This version provides the DLL for the MimerAPI module that MimerPy requires.
https://developer.mimer.com/products/downloads/

**Comment by calle5555** [comment]
I got it to work. I uninstalled everything to do with python, mimer and pip. When I reinstalled it again I noticed that my IDE ran in 32 bits even when specified to run in 64. It worked when I switched IDE.
